spring.application.name=Ecom-Kotlin-spring



server.address=0.0.0.0


server.port=8080
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:test
#//ip you can use  if   192.168.178.45

#for mobile  other wise use localhost

